configDependencies:
  pacquet: ^0.11.12

virtualStoreType: global

minimumReleaseAgeExclude:
  - "@oxfmt/*"
  - oxfmt

trustPolicy: no-downgrade
minimumReleaseAgeExcludePrune: true
trustPolicyExcludePrune: true
trustPolicyIgnoreAfter: 720
